Coletor-STF
dadosjusbr/coletor-stf pull request #1
Opened 2022-09-23 18:40 UTC by Joellensilva

2022-09-23 19:14 UTC, danielfireman requested changes

2022-09-23 19:14 UTC, danielfireman commented on src/metadado.py
> +    metadado.tem_matricula = True
Sobre lotação, cargo e matrícula, tem certeza? No CNJ eles não publicam.

2022-09-23 19:14 UTC, danielfireman commented on src/metadado.py
> +    metadado.outras_receitas = Coleta.Metadados.OpcoesDetalhamento.DETALHADO
Acho que não é detalhado. Até onde eu vi, você não processa o detalhamento de auxílios e indenizações.

2022-09-23 19:14 UTC, danielfireman commented on src/crawler.py
> +    file_path = [f'{output_path}/{filename}']
Se só retorna um arquivo, pq está criando uma lista?

2022-09-23 19:23 UTC, Joellensilva commented on src/metadado.py
> +    metadado.tem_matricula = True
Sim, sim

2022-09-23 19:29 UTC, Joellensilva commented on src/metadado.py
> +    metadado.outras_receitas = Coleta.Metadados.OpcoesDetalhamento.DETALHADO
Vou alterar

2022-09-23 19:33 UTC, Joellensilva commented on src/crawler.py
> +    file_path = [f'{output_path}/{filename}']
https://github.com/dadosjusbr/coletor-stf/blob/coletor-stf/src/main.py#L47
porque coleta.arquivos.extend(file_name) aguarda uma lista. quando passo uma string, em vez da saída ser "arquivo: /output/membros-ativos-contracheques",  a saída é: 
arquivos: /
arquivos: o
arquivos: u
arquivos: t
...

2022-09-23 20:11 UTC, danielfireman commented on src/crawler.py
> +    file_path = [f'{output_path}/{filename}']
me parece que você não está usando corretamente as variáveis. Deve alterar em outros lugares.

2022-09-23 20:11 UTC, danielfireman commented on src/metadado.py
> +    metadado.outras_receitas = Coleta.Metadados.OpcoesDetalhamento.DETALHADO
Ok. Quando terminar as alterações, favor solicitar outra revisão.

2022-10-03 15:39 UTC, danielfireman approved these changes
Bacana! Por favor, endereçar os comentários antes de realizar a consolidação.

2022-10-03 15:39 UTC, danielfireman commented on src/crawler.py
> +        headers = {
Precisamos de um comentário explicando o motivo desses cabeçalhos.

2022-10-03 15:39 UTC, danielfireman commented on src/metadado.py
> +    metadado.acesso = Coleta.Metadados.FormaDeAcesso.AMIGAVEL_PARA_RASPAGEM
temos certeza disso?

2022-10-03 18:47 UTC, merged